### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by gigisommo** [Lightricks/Kintsugi#14]
Hi!

when I try to resolve conflicts using Kintsugi I get this error:
`.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/kintsugi-0.1.1/lib/kintsugi/apply_change_to_project.rb:201:in 'apply_removal_to_simple_attribute': Value changed from  to Pods. (RuntimeError)`

The `Value changed from  to Pods` message changes based on the conflict, but the errors look all the same. I tried with two different projects without any luck.

Do you have any advice?

Thank you

**Comment by byohay** [comment]
Hi @gigisommo! 
It looks like Kintsugi identified this as a "real" merge conflict. From what I gathered, the "ours" version of the entry was `nil`, while the base commit had the string `Pods`, and "theirs" version removed it. 
This is indeed a conflict that doesn't require intervention because the end result is the same: The entry should be `nil`.
I'll try to reproduce and fix it soon.

Thanks for submitting the issue!

**Comment by byohay** [comment]
In addition the error message can probably be more indicative, I'll fix it as well.

**Comment by byohay** [comment]
@gigisommo please use the latest version and see if it works! We'll cut a release soon.

**Comment by gigisommo** [comment]
I will. Thank you very much!
